### ISSUE TITLE
پیش نیاز های برنامه | Requirements  for install

### ISSUE THREAD

**Issue by CleVeR-eRore** [ghost1372/HandySub#102]
سلام
وقت بخیر

هنگام نصب با خطای زیر مواجه میشم. گویا یکی از پیش نیاز ها کمه. راه حلی سراغ دارید؟ نسخه بتای 1 برام نصب شده بود ولی این یکی نمیشه.

App Installer failed to install package dependencies. Ask the developer for Microsoft.WindowsAppRuntime.1.0-preview2 package.

**Comment by Amin884** [comment]
> 
> 
> > سلام
> > وقت بخیر
> > هنگام نصب با خطای زیر مواجه میشم. گویا یکی از پیش نیاز ها کمه. راه حلی سراغ دارید؟ نسخه بتای 1 برام نصب شده بود ولی این یکی نمیشه.
> > App Installer failed to install package dependencies. Ask the developer for Microsoft.WindowsAppRuntime.1.0-preview2 package.
> 
> سلام مطمعن باشید که هنگام نصب اینترنت متصل باشه در نسخه های اینده تمام پیش نیاز ها بصورت افلاین ارائه خواهد شد در حال حاظر برای نصب اینترنت باید متصل باشه

سلام.اینترنت هم وصله ولی بازم برای من خطا میده.

**Comment by ghost1372** [comment]
سلام بزودی نسخه جدید بدون مشکل و بصورت Unpackaged منتشر میشه

**Comment by ghost1372** [comment]
نسخه جدید رو تست کنید
https://github.com/ghost1372/HandySub/releases/tag/v4.0.0-beta.4

**Comment by Amin884** [comment]
برای من که خطای رانتایم دسکتاپ 6 میده.با اینکه دانلود و نصبش هم کردم خطا از بین نمیره

**Comment by ghost1372** [comment]
> برای من که خطای رانتایم دسکتاپ 6 میده.با اینکه دانلود و نصبش هم کردم خطا از بین نمیره

کدوم معماری رو نصب کردید؟

**Comment by Amin884** [comment]
خودش میگه 86 ولی من نصب کردم دیدم نشد، 64 هم نصب کردم بازم نشد
