### ISSUE TITLE
compatibility windows 11

### ISSUE THREAD

**Issue by 3xploiton3** [ghost1372/HandySub#103]
v4.0.0-beta.4

cannot be installed in windows 11

i have been install
DotNet 6.0 Runtime
Windows App SDK Runtime

![image](https://user-images.githubusercontent.com/19517680/147841536-291e5797-6eaf-448e-97fc-ae6e80917e6c.png)

**Comment by benyhirmansyah** [comment]
Same issue with me with Windows 11.

**Comment by 3xploiton3** [comment]
> I think this is wasdk bug, i will release a new version later

need update soon

**Comment by ghost1372** [comment]
> > I think this is wasdk bug, i will release a new version later
> 
> need update soon

currently, self-contained (single exe file) release blocked by some WASDK bugs, so i cant make a self-contained (single exe file), I will soon add some new changes and features to the project such as mica support. but I need a little time to complete my private project

**Comment by ghost1372** [comment]
new version available https://github.com/ghost1372/HandySub/releases/tag/v4.0.0-beta.5
