### ISSUE TITLE
double click feature

### ISSUE THREAD

**Issue by 3xploiton3** [ghost1372/HandySub#97]
![image](https://user-images.githubusercontent.com/19517680/131373785-d378e2eb-1299-4158-9659-d7886b0348ad.png)

pls add double click to download subs, like old version

**Comment by ghost1372** [comment]
I will do

**Comment by ghost1372** [comment]
Done😁
you should enable this option from settings
The settings page will soon be simpler and more beautiful 😄

![Untitled](https://user-images.githubusercontent.com/9213496/131378499-f6fe5c22-13f3-4af8-9886-e71982aad977.png)

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/131862515-b9ce6614-1a4f-4a70-a2f8-7d604da32ca1.png)

if i double click image, can u make linkable sir

**Comment by ghost1372** [comment]
what do you mean by linkable?

**Comment by 3xploiton3** [comment]
> 
> 
> what do you mean by linkable?

i can click go to subs file,

**Comment by ghost1372** [comment]
> > what do you mean by linkable?
> 
> i can click go to subs file,

it's not logical, There may be problems selecting the file
