### ISSUE TITLE
title character goes wrong

### ISSUE THREAD

**Issue by 3xploiton3** [ghost1372/HandySub#98]
![image](https://user-images.githubusercontent.com/19517680/131972079-edf6c0a0-0696-432c-a204-ae7692fc30bf.png)

**Comment by ghost1372** [comment]
The title is written with characters from another language.
if you see title in isubtitle site it is **Ký Sinh Trùng**

https://isubtitles.org/ky-sinh-trung-subtitles

anyway If this problem can be solved, I will solve it soon

**Comment by ghost1372** [comment]
Thank you for report
it is now fixed
tonight i will release a new beta you can download it.

![image](https://user-images.githubusercontent.com/9213496/131987227-d771ba3b-ebfc-4038-ad41-5011f5f5b6bf.png)
